from pydantic import BaseModel
from datetime import datetime

# Schema to create a new Todo in database. (id) is auto-generated by database
class TodoCreate(BaseModel):
    task : str
    createdAt : datetime = datetime.now()
    completed : bool = False

# Schema representing a Todo
class Todo(TodoCreate):
    id:int

    class Config:
        from_attributes =True

# Schema for login Token
class Token(BaseModel):
    access_token: str
    token_type: str


class TokenData(BaseModel):
    username: str | None = None


# Schema representing a user
class User(BaseModel):
    username: str
    email: str | None = None
    firstname: str | None = None
    lastname: str | None = None

    # All todos associated with a user
    todos : list[Todo] = []     

    class Config:
        from_attributes = True


#Schema used to create a new User in Database
class UserInDB(User):
    hashed_password: str